# Generated by Django 4.2.5 on 2023-09-26 14:08

from django.db import migrations, models
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название события')),
                ('description_event', models.TextField(blank=True, verbose_name='Описание')),
                ('start_of_the_event', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_event', models.DateTimeField(default=events.models.one_week_hence, verbose_name='Дата завершения')),
                ('need_for_notification', models.BooleanField(default=True, verbose_name='Напомнить')),
            ],
        ),
    ]
