# Generated by Django 4.2.5 on 2023-09-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['start_of_the_event'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
